name: IllagerVZombies
version: '1.0-SNAPSHOT'
main: project.kompass.illagerVZombies.IllagerVZombies
api-version: '1.21'
paper-weight-mapping-namespace: mojang
authors: [ JustJaimii ]
description:
  Makes Illagers fight zombies. For Project: Kompass
